# Generated by Django 3.2.9 on 2021-12-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
