# Generated by Django 3.2.9 on 2021-12-03 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20211202_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Short description')),
                ('long_description', models.TextField(blank=True, null=True, verbose_name='Long description')),
                ('status', models.CharField(choices=[('D', 'draft'), ('P', 'published')], max_length=1)),
                ('lesson_type', models.CharField(choices=[('A', 'article'), ('Q', 'quiz')], max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', related_query_name='lessons', to='course.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
