# Generated by Django 3.2.9 on 2021-12-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20211229_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='format: required, letters, numbers, underscore, or hyphens', max_length=150, verbose_name='category safe URL'),
        ),
    ]
