# Generated by Django 3.2.9 on 2021-12-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='format: required, max-100', max_length=100, verbose_name='Category name'),
        ),
    ]
