# Generated by Django 3.2.9 on 2021-12-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20211229_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title', '-created_at'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, help_text='format: required, letters, numbers, underscore, or hyphens', max_length=150, verbose_name='lesson safe URL'),
        ),
    ]
