# Generated by Django 3.2.9 on 2022-01-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20211229_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Lesson',
            new_name='lesson',
        ),
    ]
