# Generated by Django 3.2.9 on 2022-01-07 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_rename_lesson_comment_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.CharField(help_text='format: required, max-200', max_length=200, verbose_name='question title')),
                ('answer', models.CharField(help_text='format: required, max-200', max_length=200, verbose_name='answer text')),
                ('opt1', models.CharField(help_text='format: required, max-255', max_length=200, verbose_name='1st option text')),
                ('opt2', models.CharField(help_text='format: required, max-255', max_length=200, verbose_name='2nd option text')),
                ('opt3', models.CharField(help_text='format: required, max-255', max_length=200, verbose_name='3rd option text')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='course.lesson')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
